### PR TITLE
Add text to next chapter button

### LINKED ISSUE #93: Add text to the next chapter button

### LINKED ISSUE #95: Add a typing effect

### PR DESCRIPTION
**Pull request by mdlugosz1**
I couldn't do it with pseudo selectors because it was visible even when next chapter button was hidden, so i wrapped everything into container.

obraz

### CODE REVIEW

**Review by Tudwall — COMMENTED** [review]
Nice idea! You should make the text color #402218 so it's consistent with the text though 😃

**Comment by mdlugosz1** [comment]
> Nice idea! You should make the text color #402218 so it's consistent with the text though smiley

Done!

**Review by Tudwall — APPROVED** [review]

**Comment by mdlugosz1** [comment]
Couldn't sleep so i added simple animation when hover over next button:
hover

And function that writes the story:
write

BTW. Chapter index looks neat!

**Review by Tudwall — APPROVED** [review]
That's some tasty dynamism haha

**Comment by emdevs** [comment]
Oooo it's even animated and everything lol. Looks great!

**Comment by emdevs** [comment]
I just realised that it says "Chapter 1 false", I accidentally left in the boolean that shows chapter completion status while I was doing testing for chapterIndex LOL. If you don't mind, in this PR do you mind just deleting that? I can also set up another PR but its quite a minor change

**Review by emdevs — APPROVED** [review]

**Review by DavidMatalik — APPROVED** [review]
Looks absolutely awesome =)

**Pull request merged**
