### PR TITLE
Style startPage

### LINKED ISSUE #29: Style the start page

### PR DESCRIPTION
**Pull request by DavidMatalik**
Styling differs a bit from original draft because of other fonts and game description. Feel free again to share possible improvement thoughts. I also filled real text into the placeholders - also here feel free to share your own ideas. 

Parchment is at the moment a png of size 800x712 (350kb). SVG for this image costs something. Other free parchment svgs weren't that good looking.

Container is at the moment fixed sized, doesn't adjust to different view ports. Are you okay with that?

Screenshot 2021-07-28 13:14:02

### CODE REVIEW

**Review by Tudwall — APPROVED** [review]
Looks good to me, I think the png is light enough so it doesn't slow down the page too much

**Comment by mdlugosz1** [comment]
It looks great, maybe a little more intense text shadow on description would be better?

**Review by mdlugosz1 — APPROVED** [review]

**Comment by DavidMatalik** [comment]
> It looks great, maybe a little more intense text shadow on description would be better?

Like that? Or even more?

Screenshot 2021-07-29 09:43:24

Text-Shadow Opacity could be also removed/decreased: 

Screenshot 2021-07-29 09:47:33

**Comment by mdlugosz1** [comment]
> 
> 
> > It looks great, maybe a little more intense text shadow on description would be better?
> 
> Like that? Or even more?
> 
First one is ok.

**Pull request merged**
