### PR TITLE
Implement dropping functionality

### LINKED ISSUE #2: Implement drag and drop for desktop

### PR DESCRIPTION
**Pull request by DavidMatalik**
You can see an example on how to implement dropping functionality in addition to dragging functionality here: https://github.com/DavidMatalik/dNd-jam/blob/main/src/index.js

You can see it in action here: https://davidmatalik.github.io/dNd-jam/

Some stuff also changed in the makeDraggable function, that is mainly because of the use of Prettier.

### CODE REVIEW

**Review by mdlugosz1 — COMMENTED** [review]
It work's good until i resize window, then something like this happens: 

obraz

**Review by Tudwall — COMMENTED** [review]
The red box snaps into place only the first time it gets too close to where it should be dragged, I think it should happen every time. And the resize problem @mdlugosz1 already mentionned.

**Comment by DavidMatalik** [comment]
> It work's good until i resize window, then something like this happens:

Thanks I will have a look at the issue

**Comment by DavidMatalik** [comment]
> The red box snaps into place only the first time it gets too close to where it should be dragged, I think it should happen every time.

Yeah that's the question if that is needed? I also thought about to implement it - but when the box snaps into place, there will be a success window or whatever and the chapter is over. What happens after? Maybe the draggable should even stay in this snapped place until the user clicks on "Play chapter again"?

**Comment by DavidMatalik** [comment]
> It work's good until i resize window, then something like this happens:

The resize prob should now be fixed - Check it out now again, also @Tudwall. I also fixed another thing, because draggable was sometimes a bit stuck. I thought it already was in this PR. ;) The other thing requested by @Tudwall I've done so far nothing until we are clear about if this is really needed.

**Comment by Tudwall** [comment]
> Maybe the draggable should even stay in this snapped place until the user clicks on "Play chapter again"?
After it snaps into position there should be a continue button or something before the chapter continues and the story is told.

**Comment by mdlugosz1** [comment]
> > It work's good until i resize window, then something like this happens:
> 
> The resize prob should now be fixed - Check it out now again, also @Tudwall. I also fixed another thing, because draggable was sometimes a bit stuck. I thought it already was in this PR. ;) The other thing requested by @Tudwall I've done so far nothing until we are clear about if this is really needed.

Now it works fine, but in console i've got this error: Uncaught ReferenceError: leftCon is not defined.

**Comment by DavidMatalik** [comment]
> Now it works fine, but in console i've got this error: Uncaught ReferenceError: leftCon is not defined.

Sorry about that... should have tested it more thoroughly, thank you for testing it. Fixed it now. 

@Tudwall @mdlugosz1 @emdevs could you have a look again and approve the PR if everything is alright now? If you think block the draggable into place after it snapped should be implemented already, just tell, then I do it before.

**Review by mdlugosz1 — APPROVED** [review]
Everything looks fine to me.

**Review by Tudwall — APPROVED** [review]
Looks good to me as well!

**Pull request merged**
