### PR TITLE
Write quiz-factory tests

### LINKED ISSUE #30: Write tests

### PR DESCRIPTION
**Pull request by DavidMatalik**
I'm not sure if we already agreed on a quiz object. I think it makes sense. If we agree on quiz objects the question property would make more sense in quiz-factory then in chapter-factory imo.

If you think quiz objects don't make sense we can drop this all together.

### CODE REVIEW

**Comment by Tudwall** [comment]
I started writing a quiz component, I didn't make a pull request as it's not ready yet, but you can look at the branch

**Comment by mdlugosz1** [comment]
Quiz object seems fine. I know nothing about tests, so i won't speak up about that subject.

**Review by mdlugosz1 — APPROVED** [review]

**Comment by DavidMatalik** [comment]
> I started writing a quiz component, I didn't make a pull request as it's not ready yet, but you can look at the branch

Thanks for this hint! Looked at your dummy quiz component - the only difference is the passed property (and the naming for tne answer - I can change this so that it fits the name in your dummy). I added the passed property because it would be good to save if the player already successfully mastered a quiz. If the player e.g. doesn't click directly on the  nextChapter button, but clicks on the home button he would have to do the same quiz again when he comes back to this chapter. But maybe that is already too far thinking about the possible future features/enhancement?

**Comment by Tudwall** [comment]
> I added the passed property because it would be good to save if the player already successfully mastered a quiz. 

So I'd just have to set a passed variable to true in my quiz component if they pass and we're good?

**Comment by DavidMatalik** [comment]
> So I'd just have to set a passed variable to true in my quiz component if they pass and we're good?

I think this setting to true of the passed property wouldn't happen in the quiz component but in the quizClickHandler function (if I understand your code right). And the quizClickHandler function will be defined in the game logic component. 

What the quiz component would need to do: check if the passed property is already set to true - and if this is the case the nextChapterButton should be visible. (And maybe a message like "You already solved this quiz... ")

**Comment by Tudwall** [comment]
> I think this setting to true of the passed property wouldn't happen in the quiz component but in the quizClickHandler function (if I understand your code right). And the quizClickHandler function will be defined in the game logic component.
> 
> What the quiz component would need to do: check if the passed property is already set to true - and if this is the case the nextChapterButton should be visible. (And maybe a message like "You already solved this quiz... ")

Okay! I'll do that then!

**Review by Tudwall — APPROVED** [review]

**Comment by emdevs** [comment]
Although tests are good, imo they aren't really necessary for factory functions like this. I remember with the battleship project in TOP, they stated that functions for the ship object didn't need to be written, which I think is also somewhat applicable in this case. Other than that, code looks good.

**Review by emdevs — APPROVED** [review]

**Comment by DavidMatalik** [comment]
> Although tests are good, imo they aren't really necessary for factory functions like this. I remember with the battleship project in TOP, they stated that functions for the ship object didn't need to be written, which I think is also somewhat applicable in this case. Other than that, code looks good.

Where did you read this about the ship objects in the battleship project? I can't remember that I came across such a statement.

**Pull request merged**
