### PR TITLE
Create chapter index

### LINKED ISSUE #20: Create an overview page (chapterIndex page)
Create an overview page showing all the chapters to choose from in the selected story.

### PR DESCRIPTION
**Pull request by emdevs**
Creates a chapter index page for a story. I'm not sure what callback to pass to createChapterStructure though (in my "Play" button with event listener for click). 

closes #20

### CODE REVIEW

**Comment by mdlugosz1** [comment]
For now callback is displayChapterEnd method in game logic which is passed to drag and drop when images are created. Later it will be changed to function that shows up popup window with message.

**Review by mdlugosz1 — APPROVED** [review]

**Review by DavidMatalik — APPROVED** [review]

**Review by Tudwall — APPROVED** [review]

**Comment by emdevs** [comment]
There is an issue with logic, and I'm unsure of how to adapt things. If you select a chapter from chapterIndex page, it will take you to the correct chapter HOWEVER once you complete the chapter, it may take you to the wrong next chapter. (Ex. if you start at Chapter 4 and complete it, it will take you next backwards to an uncompleted chapter, like Chapter 2). 

This is because getCurrentChapter function in the story-factory finds the next chapter by looking for the **next unfinished chapter**, and is **not** based on chapter number. 

We could create another goToNextChapter function specifically for chapterIndex, or we could change the implementation of goToNextChapter. I'm not sure what's the better approach, what do you guys think?

**the "easiest" solution would be to switch getCurrentChapter function to search for current chapter num + 1, this will cause changes to be made in logic module as well, but is this the best approach?

**Comment by Tudwall** [comment]
I think changing the implementation of goToNextChapter might be the most long-term solution, if it's not too hard or doesn't take too long

**Comment by mdlugosz1** [comment]
> This is because getCurrentChapter function in the story-factory finds the next chapter by looking for the **next unfinished chapter**, and is **not** based on chapter number.

That's right, when i was creating it i didn't take into consideration that user can start with another chapter than the first one. At least it works as intended :D

> We could create another goToNextChapter function specifically for chapterIndex, or we could change the implementation of goToNextChapter. I'm not sure what's the better approach, what do you guys think?
> 
> **the "easiest" solution would be to switch getCurrentChapter function to search for current chapter num + 1, this will cause changes to be made in logic module as well, but is this the best approach?

Maybe we will add another function in story-factory that searches for last completed chapter and returns next one which status is uncompleted? What do you think about that? Of course it probably dosen't matter which way we will choose, changes in `goToNextChapter` seem inevitable.

**Comment by Tudwall** [comment]
I was thinking, if there is a change in that part of the logic, maybe it can help me with the storyEnd home button as well since looking for an uncompleted chapter that doesn't exist is the problem as well, at least I think it can help? I'm not even sure, my brain is spaghetti today haha

**Comment by DavidMatalik** [comment]
> That's right, when i was creating it i didn't take into consideration that user can start with another chapter than the first one. At least it works as intended :D

I am not sure if I understand you guys right... The user shouldn't be able to start with another chapter then chapter 1, right? All chapters except chapter 1 should be locked and a chapter should be only unlocked when the previous chapter has been completed. Or do you think it makes sense, that users can play chapters without having the story context from previous chapters? 

I can see the problem e.g. when user completed first 4 chapters, then goes back to overview page and clicks on e.g. chapter 2 to replay it again. Then after click on next button it would take him not to chapter 3 but chapter 5.

**Comment by DavidMatalik** [comment]
> **the "easiest" solution would be to switch getCurrentChapter function to search for current chapter num + 1, this will cause changes to be made in logic module as well, but is this the best approach?

Spontaneously I would say this is the easiest approach which makes most sense to me for this issue.

**Comment by DavidMatalik** [comment]
> > **the "easiest" solution would be to switch getCurrentChapter function to search for current chapter num + 1, this will cause changes to be made in logic module as well, but is this the best approach?

Spontaneously I would say this is the easiest approach which makes most sense to me for this issue, because it works in the end for both scenarios as user expects it to work.

**Comment by DavidMatalik** [comment]
> I was thinking, if there is a change in that part of the logic, maybe it can help me with the storyEnd home button as well since looking for an uncompleted chapter that doesn't exist is the problem as well, at least I think it can help? I'm not even sure, my brain is spaghetti today haha

Spontaneously I think so too... It could help with your issue as well. Because when we check for last chapter number and in this case instead of adding currentChapterNumber + 1 we set chapterNumber = 1, then your button should work fine.

**Comment by emdevs** [comment]
> ter 1 should be locked and a chapter should be only unlocked when the previous chapter has been completed. Or do you think it makes sense, that users can play chapters without having the story context from previous chapters?

Yes the buttons for certain uncompleted chapters can be locked somehow, thats true. But it still stands that the logic needs to be changed, also to allow chapters to be replayable like you said. In that case, ill try altering it to find chapternum + 1.

**Comment by emdevs** [comment]
> > This is because getCurrentChapter function in the story-factory finds the next chapter by looking for the **next unfinished chapter**, and is **not** based on chapter number.
> 
> That's right, when i was creating it i didn't take into consideration that user can start with another chapter than the first one. At least it works as intended :D
> 
> > We could create another goToNextChapter function specifically for chapterIndex, or we could change the implementation of goToNextChapter. I'm not sure what's the better approach, what do you guys think?
> > **the "easiest" solution would be to switch getCurrentChapter function to search for current chapter num + 1, this will cause changes to be made in logic module as well, but is this the best approach?
> 
> Maybe we will add another function in story-factory that searches for last completed chapter and returns next one which status is uncompleted? What do you think about that? Of course it probably dosen't matter which way we will choose, changes in `goToNextChapter` seem inevitable.

True, its not really a bug, just needs a different implementation now that chapterIndex exists lol. 

I'm not sure I understand, why does a chapter have to be found by last completed chapter? Perhaps start button on starting page should always start at chapter 1, since chapterIndex will allow players to jump between chapters if they want.

**Comment by emdevs** [comment]
**UPDATE:**

I've managed to get chapterIndex to work, I've tested things myself and all looks fine. Chapters now flow logically in order, and there is logic now to lock certain chapters to avoid people from jumping ahead in the story. 

There are some notable changes I've made to other files, so I want to let you all know about them here.

- I've replaced getCurrentChapter function with getChapter, which works by returning a chapter based on it's chapter number. findNextChapter function now works by returning currentChapterNumber + 1.
- setCompletionStatus in Chapter module had to be changed, since chapterIndex exists, chapters can be replayed, and it would cause the completed chapters to switch back to uncomplete. 

- "Start" button in the homepage is hard coded to always start at chapter 1. Perhaps it could dynamically start wherever the person last finished in the story, this is also possible.

**Comment by mdlugosz1** [comment]
I really like this changes, good work!

**Review by mdlugosz1 — APPROVED** [review]

**Review by Tudwall — APPROVED** [review]
Great work! I'll wait for your changes to be merged to keep working on the story end home button then! 😄

**Review by DavidMatalik — APPROVED** [review]
Yeah looks also good to me.

**Pull request merged**
