### PR TITLE
Success message

### LINKED ISSUE #63: Change logic so that success message and nextButton get rendered into chapter content.

### LINKED ISSUE #64: Style chapter success popup

### PR DESCRIPTION
**Pull request by mdlugosz1**
Original idea was to add success message to  `chapterDOM` and make it hidden till user fits correct shape. But there was some problems with this approach:
1.  `chapterDOM` returns only one function that is executed immediately and we did it to make code cleaner and easier to read, so i didn't want to touch it. With that in mind i wouldn't have access to success message other than directly selecting it in game logic, which leads me to another point.
2. I didn't want to make game logic directly messing with DOM.
3. Third problem was render module which when fired removes everything from content and appends new elements. With success message we don't want that behaviour. As far as i know, we wanted it to be displayed on the top of current chapter without removing it's content.

Considering mentioned problems i decided that success-message will be in separate module and render should be changed. Now it takes two arguments: first is node or array of nodes that will be appended to content (created helper function that recognizes if it is array or not) and the second one is `clearContent`.  `clearContent` is default parameter which defines if render function should wipe out any existing content or not. Default value is set to true, so when this argument is omitted, render behaves exactly like before.

Like always, if you have another idea how to solve this problems, just let me know!

### CODE REVIEW

**Review by DavidMatalik — APPROVED** [review]
I think you came up with a great, clean solution. And it works as expected.

**Review by DavidMatalik — CHANGES_REQUESTED** [review]
Now I discovered an issue: after clicking on the popup continue button you don't get directly to the next chapter. There is still the display of chapter end and you have to click on next Button to get to the next chapter. 

I think this extra end story display should be removed.

Also: when a chapter with only text is displayed, there is the same message "Congratulations, shape fits correctly! Now you can continue your story." There should be a different message. Or you adjust the message that it fits for both.

**Comment by mdlugosz1** [comment]
Chapter end was deleted and changed text of the message. Also added some styling to it and now looks like this:
image

**Review by DavidMatalik — APPROVED** [review]
It's great now!

**Review by Tudwall — APPROVED** [review]
Love it!

**Review by emdevs — APPROVED** [review]

**Pull request merged**
