### PR TITLE
Fix story quiz

### LINKED ISSUE #76: Fix quiz bug
If user chooses wrong answer two times in first quiz, game skips second quiz and shows story end right away. Logic behind checking quiz answer should be splitted into smaller parts to avoid unnecessary code nesting.

### PR DESCRIPTION
**Pull request by mdlugosz1**
Quiz now works properly with both wrong and right answers. I moved allPassed method from QuizSummary to story-factory. One thing left to do - change alerts into messages pop up.

### CODE REVIEW

**Review by DavidMatalik — APPROVED** [review]
Must admit that I didn't look at code in detail - I trust that it is fine =) I tested the quiz stuff and it works great.

**Review by Tudwall — APPROVED** [review]
Works great!

**Comment by mdlugosz1** [comment]
In order to use message component in quiz section i made simple change, so that when button is clicked, pop up window can be closed without rendering next content.

**Review by Tudwall — APPROVED** [review]
Even better!

**Review by DavidMatalik — APPROVED** [review]
Looks great with styled popup

**Review by emdevs — APPROVED** [review]

**Pull request merged**
