### PR TITLE
Make home button work

### LINKED ISSUE #66: Implement home button
- Write the logic for the home button in the logic module and export it for use.
- Find a way to not have to render the home button on every page, maybe put it in a navbar in the html

### PR DESCRIPTION
**Pull request by Tudwall**
I tried to make the home button work, it does work but I feel like the way I did it isn't the best practice at all, what do you guys think?
should close #66

### CODE REVIEW

**Comment by mdlugosz1** [comment]
Considering how everything works it's probably the only solution. We can improve it and avoid code repetition by implementing a function in game logic that takes care of generating starting page and export it into modules that have home button but i'm not sure if it's the right way to do it.

**Review by emdevs — APPROVED** [review]

**Comment by emdevs** [comment]
Yeah this seems like a quick fix, it should do for now. Possibly another solution for the future is to have #content be a child node in one more parent div, and have that parent div contain a navbar that has home button. 

So the new structure of nodes could be like:

```html
<div id="page">
    <nav>
         <button for home page/>
   </nav>
    <div id="content"></div>   
</div>
```

Since every page will likely need a home page button, might as well put it in a navbar that exists on every page, this avoids repetition of home page button implementation in almost every page as well.

**Comment by DavidMatalik** [comment]
The way it is implemented right now, logic comes into chapterDOM, what we wanted to avoid. So I agree with @mdlugosz1 that this stuff should be rather in the logic module.

In the logic module you have the function: 

```
const startFirstChapter = () => {
    const firstChapter = story.getCurrentChapter();
    return createChapterStructure(firstChapter, displayChapterEnd);
};
```

`createChapterStructure` takes in `displayChapterEnd` as callback for what should happen when the right draggable is dropped.

I think you can create a function e.g. `displayHome` in the logic module and pass this as another callback function into `createChapterStructure`. And in `displayHome` you put nearly the same code as you did now in chapterDOM.

(You then also need to make sure in the chapterDOM module to let `createChapterStructure` take in another callback and put the callback at the appropriate place.)

**Review by DavidMatalik — CHANGES_REQUESTED** [review]
The way it is implemented right now, logic comes into chapterDOM, what we wanted to avoid. So I agree with @mdlugosz1 that this stuff should be rather in the logic module.

In the logic module you have the function:

```
const startFirstChapter = () => {
    const firstChapter = story.getCurrentChapter();
    return createChapterStructure(firstChapter, displayChapterEnd);
};
```
`createChapterStructure` takes in `displayChapterEnd` as callback for what should happen when the right draggable is dropped.

I think you can create a function e.g. `displayHome` in the logic module and pass this as another callback function into `createChapterStructure`. And in `displayHome` you put nearly the same code as you did now in chapterDOM.

Edit: `createChapterStructure` is used at another place in logic module, also here you need to adjust it to take in `displayHome` function. If something is unclear or you encounter problems, don't hesitate to ask in Discord.

(You then also need to make sure in the chapterDOM module to let `createChapterStructure` take in another callback and put the callback at the appropriate place.)

**Comment by DavidMatalik** [comment]
> Since every page will likely need a home page button, might as well put it in a navbar that exists on every page, this avoids repetition of home page button implementation in almost every page as well.

You are right, that's a good idea for the future. You could then also put the help button into the navbar.

**Comment by emdevs** [comment]
> > Since every page will likely need a home page button, might as well put it in a navbar that exists on every page, this avoids repetition of home page button implementation in almost every page as well.
> 
> You are right, that's a good idea for the future. You could then also put the help button into the navbar.

Yup, basically anything that we want always to exist across all pages.

**Comment by Tudwall** [comment]
Thanks for the input! I'm gonna try to implement your ideas!

**Comment by Tudwall** [comment]
> 
> 
> Yeah this seems like a quick fix, it should do for now. Possibly another solution for the future is to have #content be a child node in one more parent div, and have that parent div contain a navbar that has home button.
> 
> So the new structure of nodes could be like:
> 
> ```
> <div id="page">
>     <nav>
>          <button for home page/>
>    </nav>
>     <div id="content"></div>   
> </div>
> ```
> 
> Since every page will likely need a home page button, might as well put it in a navbar that exists on every page, this avoids repetition of home page button implementation in almost every page as well.

If I do that I'll have to hide the button on the all the pages that doesn't need it, is that okay?

**Comment by Tudwall** [comment]
I refactored it, it works and the logic stays in logic now, the "Back to Home" button on storyEnd isn't working though

**Comment by DavidMatalik** [comment]
> I refactored it, it works and the logic stays in logic now, the "Back to Home" button on storyEnd isn't working though

Yeah it looks great now! Yeah because you didn't pass the callback into `createStoryEnd` in logic module. And there is nothing implemented for click handler in storyEnd module so far.

**Review by DavidMatalik — APPROVED** [review]

**Review by mdlugosz1 — APPROVED** [review]

**Comment by Tudwall** [comment]
> > I refactored it, it works and the logic stays in logic now, the "Back to Home" button on storyEnd isn't working though
> 
> Yeah it looks great now! Yeah because you didn't pass the callback into `createStoryEnd` in logic module. And there is nothing implemented for click handler in storyEnd module so far.

I'm gonna commit what I did for the storyEnd home button even if it doesn't work

**Comment by Tudwall** [comment]
I took quiz off of the arguments createStoryEnd takes since it wasn't used in the function; but I have a hard time wrapping my head around making the storyEnd home button work, it's that damn zombie brain again haha

**Review by emdevs — APPROVED** [review]

**Comment by DavidMatalik** [comment]
> I refactored it, it works and the logic stays in logic now, the "Back to Home" button on storyEnd isn't working though

You know it is already a great improvement that home buttons on chapter pages work. You could also merge it like it is and because of time is running short and open a new PR for the home button on last page.

**Comment by Tudwall** [comment]
> > I refactored it, it works and the logic stays in logic now, the "Back to Home" button on storyEnd isn't working though
> 
> You know it is already a great improvement that home buttons on chapter pages work. You could also merge it like it is and because of time is running short and open a new PR for the home button on last page.

You're right, I'm gonna do that and try to resolve conflicts without breaking anything haha

**Pull request merged**
